server:
  port: 8084

deal:
  url: ${DEAL_URL}

spring:
  kafka:
    consumer:
      group-id: email_service
      bootstrap-servers: ${KAFKA_SERVER}
      auto-offset-reset: earliest

application:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    transport-protocol: smtp
    smtp-auth-enabled: true
    smtp-starttls-enabled: true
    debug-enabled: true